version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install
                command: npm install
            - run:
                name: Lint
                command: npm run lint
            - run: 
                name: Test
                command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
            - run:
                name: E2E
                command: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
workflows:
    build-and-test:
      jobs:
        - build-and-test